version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./build/app/Dockerfile.dev
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./src:/home/node/app/src:rw
    networks:
      - room-rental

networks:
  room-rental:
    external: true
